### ISSUE TITLE
Missing artifact me.rayzr522:jsonmessage:jar:1.2.1

### ISSUE THREAD

**Issue by SkytAsul** [PlaceholderAPI/PlaceholderAPI#398]
### Issue
> What is the issue? Describe it like you would tell a friend.

Adding the PlaceholderAPI dependency to my project pom.xml causes this maven error: `Missing artifact me.rayzr522:jsonmessage:jar:1.2.1`

### How to reproduce
> What steps did you made, to get this bug?

```xml
<repository>
	<id>placeholderapi</id>
	<url>http://repo.extendedclip.com/content/repositories/placeholderapi/</url>
</repository>
<dependency>
	<groupId>me.clip</groupId>
	<artifactId>PlaceholderAPI</artifactId>
	<version>2.10.7</version>
	<scope>provided</scope>
</dependency>
```

[Request change (Wiki)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_wiki.md
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Spigot]: https://www.spigotmc.org/resources/6245/
[Jenkins]: http://ci.extendedclip.com/job/PlaceholderAPI/
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues

**Comment by Sxtanna** [comment]
change the artifact to completely lowercase, this issue is fixed.

**Comment by SkytAsul** [comment]
It does not fix the issue. Please reopen.
```xml
		<dependency>
			<groupId>me.clip</groupId>
			<artifactId>placeholderapi</artifactId>
			<version>2.10.7</version>
			<scope>provided</scope>
		</dependency>
```
`Missing artifact me.rayzr522:jsonmessage:jar:1.2.1`

**Comment by extendedclip** [comment]
This is fixed in dev builds. Will be fixed in the release later today/tomorrow

**Comment by Sxtanna** [comment]
> It does not fix the issue. Please reopen.
> ```xml
> 		<dependency>
> 			<groupId>me.clip</groupId>
> 			<artifactId>placeholderapi</artifactId>
> 			<version>2.10.7</version>
> 			<scope>provided</scope>
> 		</dependency>
> ```
> `Missing artifact me.rayzr522:jsonmessage:jar:1.2.1`
> 
> Using me.clip:placeholderapi:2.10.6 is working fine.
> 
> EDIT: by the way [this wiki page](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Hook-into-PlaceholderAPI#import-with-maven) demands the UpperCamelCase artifact ID "PlaceholderAPI".

It does fix the issue, you're using maven. Clear your local cache.

**Comment by Andre601** [comment]
I've updated the wiki with the accurate info.
