### ISSUE TITLE
Placeholderapi Worldguard Expansion

### ISSUE THREAD

**Issue by Imortalshard** [PlaceholderAPI/PlaceholderAPI#66]
Hi,
When trying use placeholders from the worldguard papi expansion. I'm getting this error: https://pastebin.com/cggqzZzQ

I think placeholderapi needs a more updated expansion for worldguard. As both plugins are using the latest version. So it has to be the expansion itself. 

Thanks,
Imortalshard.

**Comment by Andre601** [comment]
This might actually be the case according to the error (`NoSuchMethodError`)

Why do plugins always have to make breaking API-changes? 🙄

**Comment by Andre601** [comment]
Should this perhaps be moved to the WorldGuard repository? Or even closed? I don't know if this isn't already fixed by now.

**Comment by Imortalshard** [comment]
Apparently this hasn't been fixed yet. I've updated Worldguard to latest stable build and made sure the papi expansion was up to date and i'm still getting the same error: https://pastebin.com/BkTsGmcW
